### PR TITLE
npm bump, grunt fixes

### PR DESCRIPTION
**Pull request by rdepena**

### CODE REVIEW

**Comment by lostintangent** [comment]
@rdepena #20 is my last PR of improvements for VS Code + OpenFin, so it would be great if we could get that included a newer NPM release. Thanks!

**Comment by rdepena** [comment]
@lostintangent Should be in 0.3.4.

Also it should no longer complain on es6 syntax.

**Comment by lostintangent** [comment]
@rdepena Hmm OK. I just installed `0.3.4`, and the app it generates doesn't seem to include my changes in #20.

**Comment by rdepena** [comment]
Jaja, ok, 24 mins ago,  I tough you were referring to the  json schema changes.

**Pull request merged**
