### PR TITLE
Adding VS Code debug attach config

### PR DESCRIPTION
**Pull request by lostintangent**
This PR adds a VS Code "launch config" file, which allows users to easily attach the VS Code integrated debugger to an OpenFin app *(see image below)*. This provides an alternative to the Chrome DevTools, and allows setting breakpoints within VS Code, stepping, evaluating expressions in the console, etc. without having to leave the editor.

With this in place, the user can run the `grunt serve` task to startup the connect server and launch their OpenFin app, and then hit `F5` to attach the VS Code debugger to the app. 

image

This debug config relies on the `Debugger for Chrome` extension for VS Code being installed, but if the user doesn't already have this installed, the `extensions.json` file will trigger VS Code to recommend they install it. This provides a "guided" experience for users getting their workspace setup.

image

### CODE REVIEW

**Comment by rdepena** [comment]
:+1:

**Comment by lostintangent** [comment]
@rdepena Thanks! Any thoughts on doing an 0.3.5 release with these changes?

**Comment by rdepena** [comment]
@lostintangent yea, doing that now.

**Comment by rdepena** [comment]
@lostintangent should be available now.

**Comment by lostintangent** [comment]
Yay! Thanks so much

**Pull request merged**
